# Generated by Django 5.0.6 on 2025-03-25 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rank'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class',
        ),
    ]
