# Generated by Django 5.2 on 2025-05-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('movie_title', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(max_length=5000)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
