from cities.models import AquaPark
from cities.models import City

city_1 = City(name="", description="a")
city_1.save()
city_2 = City(name="", description="a")
city_2.save()
city_ = City(name="", description="a")
city_.save()
city_ = City(name="", description="a")
city_.save()
city_ = City(name="", description="a")
city_.save()
city_ = City(name="", description="a")
city_.save()
city_ = City(name="", description="a")
city_.save()
city_ = City(name="", description="a")
city_.save()
city_ = City(name="", description="a")
city_.save()
city_ = City(name="", description="a")
city_.save()

aquapark_1 = AquaPark(name="", address="", description="a")
aquapark_1.save()
aquapark_2 = AquaPark(name="", address="", description="a")
aquapark_2.save()
aquapark_ = AquaPark(name="", address="", description="a")
aquapark_.save()
aquapark_ = AquaPark(name="", address="", description="a")
aquapark_.save()
aquapark_ = AquaPark(name="", address="", description="a")
aquapark_.save()
aquapark_ = AquaPark(name="", address="", description="a")
aquapark_.save()
aquapark_ = AquaPark(name="", address="", description="a")
aquapark_.save()
aquapark_ = AquaPark(name="", address="", description="a")
aquapark_.save()
aquapark_ = AquaPark(name="", address="", description="a")
aquapark_.save()
aquapark_ = AquaPark(name="", address="", description="a")
aquapark_.save()
aquapark_ = AquaPark(name="", address="", description="a")
aquapark_.save()
aquapark_ = AquaPark(name="", address="", description="a")
aquapark_.save()
aquapark_ = AquaPark(name="", address="", description="a")
aquapark_.save()
aquapark_ = AquaPark(name="", address="", description="a")
aquapark_.save()
aquapark_ = AquaPark(name="", address="", description="a")
aquapark_.save()
aquapark_ = AquaPark(name="", address="", description="a")
aquapark_.save()
aquapark_ = AquaPark(name="", address="", description="a")
aquapark_.save()
aquapark_ = AquaPark(name="", address="", description="a")
aquapark_.save()
aquapark_ = AquaPark(name="", address="", description="a")
aquapark_.save()
aquapark_ = AquaPark(name="", address="", description="a")
aquapark_.save()