# Generated by Django 5.0.6 on 2025-02-01 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_message_publish_time_alter_message_publish_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='title',
        ),
    ]
