from list.models import Product
from list.models import Review
from decimal import Decimal
from list import average

product_1 = Product(name="Cheese", cost=Decimal("2.35"))
product_1.save()
product_2 = Product(name="Milk", cost=Decimal("2.5"))
product_2.save()
product_3 = Product(name="Eggs", cost=Decimal("3.25"))
product_3.save()
product_4 = Product(name="Sour Cream", cost=Decimal("4.05"))
product_4.save()

review_1 = Review(product=product_1, grade=3, text="")
review_1.save()
review_2 = Review(product=product_1, grade=4, text="")
review_2.save()
review_3 = Review(product=product_1, grade=2, text="")
review_3.save()
review_4 = Review(product=product_1, grade=4, text="")
review_4.save()
review_5 = Review(product=product_1, grade=5, text="")
review_5.save()
review_6 = Review(product=product_2, grade=3, text="")
review_6.save()
review_7 = Review(product=product_2, grade=4, text="")
review_7.save()
review_8 = Review(product=product_2, grade=2, text="")
review_8.save()
review_9 = Review(product=product_2, grade=3, text="")
review_9.save()
review_10 = Review(product=product_2, grade=2, text="")
review_10.save()
review_11 = Review(product=product_3, grade=5, text="")
review_11.save()
review_12 = Review(product=product_3, grade=2, text="")
review_12.save()
review_13 = Review(product=product_3, grade=4, text="")
review_13.save()
review_14 = Review(product=product_3, grade=5, text="")
review_14.save()
review_15 = Review(product=product_3, grade=4, text="")
review_15.save()
review_16 = Review(product=product_4, grade=1, text="")
review_16.save()
review_17 = Review(product=product_4, grade=1, text="")
review_17.save()
review_18 = Review(product=product_4, grade=4, text="")
review_18.save()
review_19 = Review(product=product_4, grade=4, text="")
review_19.save()
review_20 = Review(product=product_4, grade=3, text="")
review_20.save()