from courses_students.models import Student, Course

st1 = Student(name="Ivan", email="Ivan@email.com")
st1.save()
st2 = Student(name="Josh", email="Josh@email.com")
st2.save()
st3 = Student(name="Donald", email="Donald@email.com")
st3.save()
st4 = Student(name="Pranav", email="Pranav@email.com")
st4.save()
st5 = Student(name="Michael", email="Michael@email.com")
st5.save()

c1 = Course(title="Math", description="")
c1.save()
c2 = Course(title="History", description="")
c2.save()
c3 = Course(title="Chemistry", description="")
c3.save()
c4 = Course(title="Literature", description="")
c4.save()
c5 = Course(title="", description="")
c5.save()

c1.students.add(st1, st2, st3)
c1.save()
c2.students.add(st2, st4, st5)
c2.save()