# Generated by Django 5.0.6 on 2025-04-05 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_delete_class'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rank',
        ),
    ]
