# Generated by Django 5.0.6 on 2025-03-21 16:11

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_isbn_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(default=books.models.random_number, max_length=13),
        ),
    ]
