# Generated by Django 5.0.6 on 2025-03-20 16:58

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(default=books.models.generate_isbn, max_length=13, unique=True),
        ),
    ]
