# Generated by Django 5.0.6 on 2025-04-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('emblem', models.ImageField(default='profile_pics/anonymous.png', upload_to='ranks')),
            ],
        ),
    ]
