# Generated by Django 5.0.6 on 2025-03-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rank'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rank',
            field=models.ManyToManyField(related_name='users', to='main_app.rank'),
        ),
    ]
